version: "3.9"  # optional since v1.27.0
services:
  keys_ms:
    container_name: firma_keys_ms    
    build: 
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 8093:8093

