FROM node:16

# Create app directory
WORKDIR /usr/src/app

COPY ./src ./src

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
RUN yarn install

# Set the container port
ENV PORT=8093

EXPOSE 8093
# Launch:
CMD ["npm", "run", "start"]